Traceback (most recent call last):
  File "/Users/georgioszefkilis/MLOps_DTU-1/03_Visualization/train_wandb.py", line 192, in <module>
    main()
  File "/Users/georgioszefkilis/anaconda3/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/georgioszefkilis/anaconda3/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/georgioszefkilis/anaconda3/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/georgioszefkilis/anaconda3/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/georgioszefkilis/MLOps_DTU-1/03_Visualization/train_wandb.py", line 60, in main
    train_set_targets = train_set.targets.numpy()
AttributeError: 'Subset' object has no attribute 'targets'
